config/routes.rb
ForgeTeam::Application.routes.draw do
  root to: "static_pages#root"
  get "static_pages/about"
  get "static_pages/contact"
  get "sessions/login_guest"
  
  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index, :show, :update]
    resources :teams, only: [:create, :index, :show, :update, :destroy]
    resources :memberships, only: [:create, :index, :show, :update, :destroy]
  end
  
  resources :users, only: [:new, :create]
  resource  :session, only: [:new, :create, :destroy]
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  validates :user_id, presence: true
  validates :team_id, presence: true
  validates :rank, presence: true
  validates :user_id, :uniqueness => { scope: :team_id }
  belongs_to :user, class_name: "User"
  belongs_to :team, class_name: "Team"
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates :teamname, presence: true, uniqueness: true
  
  has_many :memberships, foreign_key: :team_id, class_name: "Membership"
  has_many :users, through: :memberships, source: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, presence: { message: "Please provide a username."}, uniqueness: true 
  validates :fname, presence: { message: "Please provide a first name!" }
  validates :lname, presence: { message: "Please provide a last name!" }
  validates :password_digest, presence: { message: "Please provide a PW at least 6 characters long" }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true

  before_validation :ensure_session_token
  
  has_many :memberships, foreign_key: :user_id, class_name: "Membership"
  has_many :teams, through: :memberships, source: :team
  
  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
  end
end

app/controllers/api/memberships_controller.rb
module Api
  class MembershipsController < ApiController
    def create
      @membership = Membership.new(membership_params)
      
      if @membership.save
        render json: @membership
      else
        render json: @membership.errors.full_messages, status: 422
      end
    end
    
    def index
      @memberships = Membership.all
      render json: @memberships
    end
    
    def show
      @membership = Membership.find(params[:id])
      
      if @membership
        render json: @membership
      else
        render json: @membership.errors.full_messages, status: 422
      end
    end
    
    def update
      @membership = Membership.find(params[:id])
      
      if @membership.update_attributes(membership_params)
        render json: @membership
      else
        render json: @membership.errors.full_messages, status: 422
      end
    end
    
    def destroy
      @membership = Membership.find(params[:id])
      
      if @membership.destroy
        render json: @membership
      else
        render json: @membership.errors.full_messages, status: 422
      end
    end
    
    private
    def membership_params
      params.require(:membership).permit(:user_id, :team_id, :rank, :seat)
    end
  end
end

app/controllers/api/teams_controller.rb
module Api
  class TeamsController < ApiController
    def index
      @teams = Team.all
      # render json: @teams
      render :index
    end
    
    def show
      @user = current_user
      @team = Team.find(params[:id])
      
      if @team
        render :show
      else
        render json: @team.errors.full_messages, status: 422
      end
    end
    
    def update
      @team = Team.find(params[:id])
      
      if @team.update_attributes(team_params)
        render json: @team
      else
        render json: @team.errors.full_messages, status: 422
      end
    end
    
    def create
      @team = Team.new(team_params)
      if @team.save
        render :json => @team
      else
        render :json => @team.errors.full_messages, :status => 422
      end
    end
    
    private
    
    def team_params
      params.require(:team).permit(:teamname, :sports_id)
    end
    
  end
  
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApiController
    def index
      @users = User.all
      render json: @users
    end
    
    def show
      @user = User.find(params[:id])
      
      if @user
        render json: @user
      else
        render json: @user.errors.full_messages, status: 422
      end
    end
    
    def update
      @user = User.find(params[:id])
      
      if @user.update_attributes(user_params)
        render json: @user
      else
        render json: @user.errors.full_messages, status: 422
      end
    end
    
    private
    def user_params
      params.require(:user).permit(:username, :password, :weight, :height, :side)
    end
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery

  # Expose these methods to the views
  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end

  def require_signed_out!
    redirect_to user_url(current_user) if signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_signed_out!, :only => [:new, :create]
  before_action :require_signed_in!, :only => [:destroy]

  def new
  end
  
  def login_guest
    params[:user] = {:username => "Guest", :password => "guest123"}    
    
    @user = User.find_by_credentials(
      user_params[:username],
      user_params[:password]
    )
    
    if @user
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Guest user account has issues"]
      render :new
    end
  end
  
  def create
    @user = User.find_by_credentials(
      user_params[:username],
      user_params[:password]
    )
  
    if @user
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end
  
  def destroy
    sign_out
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_in!, only: [:show]
  before_action :require_signed_out!, only: [:create, :new]

  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    render json: @user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to "/"
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new, status: 422
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :fname, :lname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forge Team</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  
  <body class>
      <nav class="navbar navbar-inner navbar-fixed_top my-navbar" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#demo-project-navbar-collapse-1">
          <!-- this is the unicode character that approximates a menu icon.
          Better to get an image in your own app. -->
          &#9776;
        </button>
        <img src="/assets/floaters.jpg" height="50" width="68.2">
      </div>
      <div class="collapse navbar-collapse" id="demo-project-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_url %></li>
          <li><a href="#/about">About</a></li>
          <li><a href="#/contact">Contact</a></li>
<!--          <li><%= link_to "About", static_pages_about_url %></li>
          <li><%= link_to "Contact", static_pages_contact_url %></li>
-->
          <%if current_user%>
          <li class="dropdown"> 
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.fname %> <%= current_user.lname %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#/user/edit">Profile</a></li>
            <li class="divider"></li>
            <li><%= link_to "Log Out", session_url, method: :delete %></li>
          <% end %>
          </ul>
          </li>
            <!-- <% else %> -->
          <!-- <li><a href="/session/new" data-toggle="modal" data-target=".bs-modal-sm" data-toggle="popover">Sign In</a></li> -->
          <!-- <li><%= link_to "Sign In", new_session_url, method: :get%></li> -->
        </ul>
      </div>
      </nav>

    <!-- <% if signed_in? %>
    <ul>
      <li>Currently signed in as: <%= current_user.username %></li>
      <li><%= link_to "Sign Out", session_url, :method => :delete %></li>
    </ul>
    <% else %>
    <p>
      <%= link_to "Sign In", new_session_url %> or
      <%= link_to "Sign up", new_user_url %>
    </p>
    <% end %> -->

    <% if flash[:errors] %>
    <h3>Please fix the following errors:</h3>
    <ul>
      <% flash[:errors].each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>
    <% end %>
    
    <%= yield %>

    <!-- <img src="/assets/bang_dboat_sfti.jpeg" class="fix opaque" height="256" width="384"> -->
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-2">
    </div>
    <div class="col-xs-8">
      <h3>About</h3>
      ForgeTeam was created by Andrew Chen as a final project for App Academy. The purpose is to create an app for sports team management. For this particular example, the sport was limited to dragonboat. Parts of this website will be implemented as a live version with more features for an actual dragon boat team.
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-2">
    </div>
    <div class="col-xs-8">
      <h3>Contact</h3>
      E-mail: <a href="mailto:e-mail@email.com">Andrew Chen</a>.<br>
    </div>
  </div>
</div>

app/views/static_pages/root.html.erb
<html>
  <head>
    <style>
      .nopadding {
        padding: 0 !important;
        margin: 0 !important;
      }
      
      body {
          background-color: #fff;
  
        }
        signin.btn 
        {
         outline:0;
         border:none;
         border-top:none;
         border-bottom:none;
         border-left:none;
         border-right:none;
         box-shadow:inset 2px -3px rgba(0,0,0,0.15);
         color: #70E300;
         background-color: #000;
        }
        .btn:focus
        {
         outline:0;
         -webkit-outline:0;
         -moz-outline:0;
        }
        
        signin.btn:hover
        {
          color: #70E300;
          background-color: #000;
        }
        .fullscreen_bg {
          position: fixed;
          top: 0;
          right: 0;
          bottom: 0;
          left: 0;
          background-size: cover;
          background-position: 50% 50%;
/*          background-image: url('http://cleancanvas.herokuapp.com/img/backgrounds/color-splash.jpg');*/
          background-repeat:repeat;
        }
        .form-signin {
          max-width: 280px;
          padding: 15px;
          margin: 0 auto;
            margin-top:50px;
        }
        .form-signin .form-signin-heading, .form-signin {
          margin-bottom: 10px;
        }
        .form-signin .form-control {
          position: relative;
          font-size: 16px;
          height: auto;
          padding: 10px;
          -webkit-box-sizing: border-box;
          -moz-box-sizing: border-box;
          box-sizing: border-box;
        }
        .form-signin .form-control:focus {
          z-index: 2;
        }
        .form-signin input[type="text"] {
          margin-bottom: -1px;
          border-bottom-left-radius: 0;
          border-bottom-right-radius: 0;
          border-top-style: solid;
          border-right-style: solid;
          border-bottom-style: none;
          border-left-style: solid;
          border-color: #000;
        }
        .form-signin input[type="password"] {
          margin-bottom: 10px;
          border-top-left-radius: 0;
          border-top-right-radius: 0;
          border-top-style: none;
          border-right-style: solid;
          border-bottom-style: solid;
          border-left-style: solid;
          border-color: rgb(0,0,0);
          border-top:1px solid rgba(0,0,0,0.08);
        }
        .form-signin-heading {
          color: #000;
          text-align: center;
/*          text-shadow: 0 2px 2px rgba(0,0,0,0.5);*/
        }
    </style>
  </head>
  <body id="bkimage" class="opaque">
    <% if current_user %>
    <h1 align="center"><%= current_user.fname %> <%= current_user.lname %></h1>
    
    <div class="container">

      <div id="content">
        <div class="row">
          <div class="col-xs-12 nopadding">
          </div>
    <% else %>
    
    <div id="fullscreen_bg" class="fullscreen_bg"/>

    <div class="container">

    	<form class="form-signin" action="<%= session_url %>" method="post">
        <input
           name="authenticity_token"
           type="hidden"
           value="<%= form_authenticity_token %>">
           <h2 class="form-signin-heading text-muted">Sign In</h2>
    		<input type="text" class="form-control" placeholder="Username" required="" autofocus="" name="user[username]">
    		<input type="password" class="form-control" placeholder="Password" required="" name="user[password]">
    		<button class="signin.btn btn-lg btn-primary btn-block" type="submit">
    			Sign In
    		</button>
        New User? <%= link_to "Sign Up", new_session_url, method: :get %><br>
        Trying Out? <%= link_to "Guest Sign In", sessions_login_guest_url, method: :get%>
    	</form>

    </div>
    
    <% end %>
    </div>
    </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

<script>
  <% if current_user %>
    window.userId = <%= current_user.id %>
  <% end %>
  $(function () {
  });
</script>

app/views/users/_form.html.erb
<html>
  <head>
    <style>
      body {
          background-color: #fff;
  
        }
        signin.btn 
        {
         outline:0;
         border:none;
         border-top:none;
         border-bottom:none;
         border-left:none;
         border-right:none;
         box-shadow:inset 2px -3px rgba(0,0,0,0.15);
         color: #70E300;
         background-color: #000;
        }
        .btn:focus
        {
         outline:0;
         -webkit-outline:0;
         -moz-outline:0;
        }
        
        signin.btn:hover
        {
          color: #70E300;
          background-color: #000;
        }
        .fullscreen_bg {
          position: fixed;
          top: 0;
          right: 0;
          bottom: 0;
          left: 0;
          background-size: cover;
          background-position: 50% 50%;
/*          background-image: url('http://cleancanvas.herokuapp.com/img/backgrounds/color-splash.jpg');*/
          background-repeat:repeat;
        }
        .form-signin {
          max-width: 280px;
          padding: 15px;
          margin: 0 auto;
            margin-top:50px;
        }
        .form-signin .form-signin-heading, .form-signin {
          margin-bottom: 10px;
        }
        .form-signin .form-control {
          position: relative;
          font-size: 16px;
          height: auto;
          padding: 10px;
          -webkit-box-sizing: border-box;
          -moz-box-sizing: border-box;
          box-sizing: border-box;
        }
        .form-signin .form-control:focus {
          z-index: 2;
        }
        .form-signin input[type="text"] {
          margin-bottom: -1px;
          border-bottom-left-radius: 0;
          border-bottom-right-radius: 0;
          border-top-style: solid;
          border-right-style: solid;
          border-bottom-style: none;
          border-left-style: solid;
          border-color: #000;
        }
        .form-signin input[type="password"] {
          margin-bottom: 10px;
          border-top-left-radius: 0;
          border-top-right-radius: 0;
          border-top-style: none;
          border-right-style: solid;
          border-bottom-style: solid;
          border-left-style: solid;
          border-color: rgb(0,0,0);
          border-top:1px solid rgba(0,0,0,0.08);
        }
        .form-signin-heading {
          color: #000;
          text-align: center;
/*          text-shadow: 0 2px 2px rgba(0,0,0,0.5);*/
        }
    </style>
  </head>
  <body>
    <% action = (user.persisted? ? user_url(user) : users_url) %>
    <% method = (user.persisted? ? "put" : "post") %>
    <% message = (user.persisted? ? "Update user" : "Create user") %>
    
    <div id="fullscreen_bg" class="fullscreen_bg"/>

    <div class="container">

    	<form class="form-signin" action="<%= action %>" method="post">
        <input
           name="_method"
           type="hidden"
           value="<%= method %>">
        <input
           name="authenticity_token"
           type="hidden"
           value="<%= form_authenticity_token %>">
    		<h2 class="form-signin-heading text-muted">Sign Up</h2>
        <input type="text" class="form-control" placeholder="First Name" required="" name="user[fname]">
        <input type="text" class="form-control" placeholder="Last Name" required="" name="user[lname]">
    		<input type="text" class="form-control" placeholder="Username" required="" autofocus="" name="user[username]">
    		<input type="password" class="form-control" placeholder="Password" required="" name="user[password]">
    		<button class="signin.btn btn-lg btn-primary btn-block" type="submit">
    			Sign In
    		</button>
        New User? <%= link_to "Sign Up", new_user_url, method: :get %>
        <br>
        Trying Out? <%= link_to "Sign Up", sessions_login_guest_url, method: :post %>
    	</form>

    </div>
    
  </body>
</html>

app/views/users/new.html.erb
<div class="container">
  <%= render "form", :user => @user %>
</div>

app/views/users/show.html.erb
<p>Manage team</p>
<div id="content">
</div>